version: '3.8'

services:
  web:
    build: .
    working_dir: /app/backend         
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./backend:/app/backend      
    env_file:
      - .env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME:-db}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - DATABASE_NAME=${DATABASE_NAME:-app_db}
#    depends_on:
#      - db

# db:
#   image: postgres:13
#   ports:
#     - "${DATABASE_PORT:-5432}:5432"
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   environment:
#     - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
#     - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
#     - POSTGRES_DB=${DATABASE_NAME:-app_db}

# volumes:
#   postgres_data:
